### ISSUE TITLE
Tratamento de exceção

### ISSUE THREAD

**Issue by oliveiralex** [fabiuhp/exercMod01#1]
Caro Fábio,

Sou o Alexandre e estou corrigindo o seu projeto. Seu trabalho foi aceito, parabéns! Para ficar 100%, falta incluir o tratamento de exceção. Está retornando o erro 500 ao buscar (GET), atualizar (PUT) e excluir (DELETE) um usuário com código que não existe.

Assim que você fizer o tratamento, peço que você me informe para que eu feche a issue.

Abraço e bons estudos

**Comment by fabiuhp** [comment]
Olá Alexandre, obrigado a informação. Acrescentei um try catch dentro do findById(service) que eu não tinha feito, porém o erro permanece. Conseguiria me dar um suporte pra entender o motivo de não parar no elseThrow?

**Comment by oliveiralex** [comment]
Caro Fábio,

Sugiro que você assista a aula "Tratamento de exceções" onde o Nélio aborda o passo a passo para fazer este tratamento.

**Comment by fabiuhp** [comment]
Show! Agradeço o comentário! Fiz as correções @oliveiralex

**Comment by oliveiralex** [comment]
Obrigado Fábio!
